_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 49
                - 55
                - 105
            "2":
                - 49
                - 55
                - 105
            "3":
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
